development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_secret: <%= ENV['JWT_SECRET'] %>
  cloudinary_user: <%= ENV['CLOUDINARY_USER'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  jwt_secret: <%= ENV['JWT_SECRET'] %>
  cloudinary_user: <%= ENV['CLOUDINARY_USER'] %>